"use client";
import { useState } from "react";
import MonitoringCharts from "@/components/crm/MonitoringCharts";
import { Card, Notice, DateRangePicker, Table, td, tdNum, num, useApi, fieldCls, btnCls } from "@/components/crm/ui";
import { modelLabel } from "@/lib/modelLabel";
type Metrics = {attempts:number;requests:number;retries:number;success:number;bad_request:number;client_error:number;server_error:number;other_http:number;timeout:number;network_error:number;cancelled:number;avg_ms:number|null};
type Data = {period:{from:string;to:string};totals:Metrics;statuses:{http_status:number|null;outcome:string;count:number}[];models:(Metrics & {model:string;provider:string})[];series:(Metrics & {date:string})[];options:string[];firstRecordedAt:string|null};
const outcomeLabel: Record<string,string> = {timeout:"逾時（無 HTTP 狀態）",network_error:"連線失敗（無 HTTP 狀態）",cancelled:"取消／中止"};
export default function ModelMonitoringPage() {
 const [days,setDays]=useState(7);const [range,setRange]=useState("");const [model,setModel]=useState("");
 const api=useApi<Data>(`/api/crm/monitoring?${range || `days=${days}`}${model ? `&model=${encodeURIComponent(model)}` : ""}`);
 const totals=api.data?.totals;
 return <div className="space-y-6">
  <header className="space-y-3"><p className="text-xs tracking-[.2em] text-[#7ff0cd]">MODEL OBSERVABILITY</p><h1 className="text-2xl font-semibold text-white">模型使用量監控</h1><p className="max-w-3xl text-sm leading-7 text-[#aaa]">查看上游請求量、HTTP 狀態與連線異常。日期以台灣時間計算，起訖日均包含在內。</p></header>
  <div className="flex flex-wrap items-center gap-3"><label className="min-w-0 max-w-full text-xs text-[#aaa]">模型<select aria-label="篩選模型" className={`${fieldCls} ml-2 max-w-full`} value={model} onChange={e=>setModel(e.target.value)}><option value="">全部模型</option>{api.data?.options.map(id=><option key={id} value={id}>{modelLabel(id)} · {id}</option>)}</select></label><DateRangePicker days={range ? 0 : days} onDays={n=>{setDays(n);setRange("");}} onRange={(from,to)=>setRange(`from=${from}&to=${to}`)} /><button onClick={api.reload} className={btnCls}>重新整理</button></div>
  {api.error && <Notice kind="err">{api.error}</Notice>}
  <Notice kind="info">HTTP 2xx 表示上游接受或回應成功，不保證非同步影片已生成。400 屬於請求錯誤，並包含在 4xx 總數內。每次備用 Key 重試各計一筆 HTTP 嘗試，但同一請求合併計入「請求數」。影片輪詢不列入使用量。</Notice>
  <p className="text-xs leading-6 text-[#888]">涵蓋 SIRAYA 模型提交、Google 語音與 Vercel Jev 背景評估；不包含本站送出前拒絕的驗證／扣點錯誤、串流中途錯誤或影片最終結果。自本版本開始記錄，歷史沒有狀態碼的資料不回填。{api.data?.firstRecordedAt ? `首筆紀錄：${new Date(api.data.firstRecordedAt).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"})}` : "目前尚無監控紀錄；零筆不代表歷史沒有使用。"}</p>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["請求數",totals?.requests],["HTTP 嘗試數",totals?.attempts],["HTTP 2xx",totals?.success],["HTTP 400",totals?.bad_request],["HTTP 4xx（含 400）",totals?.client_error],["HTTP 5xx",totals?.server_error],["逾時／連線／中止",totals ? totals.timeout+totals.network_error+totals.cancelled : undefined],["備用 Key 重試",totals?.retries]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[#292929] bg-[#121212] p-4"><p className="text-xs text-[#999]">{label}</p><p className="mt-2 text-2xl tabular-nums text-white">{value === undefined ? "—" : num(Number(value))}</p></div>)}</div>
  {api.data && <MonitoringCharts period={api.data.period} series={api.data.series} models={api.data.models} statuses={api.data.statuses} />}
  <Card title="狀態碼分布" sub="相同 HTTP 狀態碼合併計數；沒有收到 HTTP 回應的連線異常分開列出。"><div className="flex flex-wrap gap-3">{api.data?.statuses.map(s=><div key={`${s.http_status}:${s.outcome}`} className="rounded-xl border border-[#303030] px-4 py-3"><p className={`text-sm ${s.http_status && s.http_status>=400 ? "text-[#ffb4b4]" : "text-[#ccc]"}`}>{s.http_status === null ? outcomeLabel[s.outcome] ?? s.outcome : `HTTP ${s.http_status}`}</p><p className="mt-1 text-xl text-white">{num(s.count)}</p></div>)}{api.data?.statuses.length===0 && <p className="text-sm text-[#999]">此篩選區間沒有已記錄的請求。</p>}</div></Card>
  <Card title="各模型使用量" sub="平均回應時間計算至收到 HTTP 回應標頭，不是完整影片生成耗時。"><Table minWidth={980} head={["模型／來源","請求","嘗試","2xx","400","全部 4xx","5xx","連線異常","其他 HTTP","重試","平均回應 ms"]}>{api.data?.models.map(r=><tr key={r.model}><td className={td}><div>{modelLabel(r.model)}</div><div className="max-w-64 break-all text-xs text-[#888]">{r.model}<br />{r.provider}</div></td>{[r.requests,r.attempts,r.success,r.bad_request,r.client_error,r.server_error,r.timeout+r.network_error+r.cancelled,r.other_http,r.retries,r.avg_ms].map((n,i)=><td key={i} className={tdNum}>{n===null ? "—" : num(n)}</td>)}</tr>)}</Table></Card>
  <Card title="每日明細" sub={api.data ? `${api.data.period.from} — ${api.data.period.to} · 僅列有紀錄的日期` : "載入中"}><Table minWidth={680} head={["日期","請求","嘗試","2xx","400","全部 4xx","5xx","連線異常","重試"]}>{api.data?.series.map(r=><tr key={r.date}><td className={td}>{r.date}</td>{[r.requests,r.attempts,r.success,r.bad_request,r.client_error,r.server_error,r.timeout+r.network_error+r.cancelled,r.retries].map((n,i)=><td key={i} className={tdNum}>{num(n)}</td>)}</tr>)}</Table></Card>
 </div>;
}
