"use client";
import { useState } from "react";
export default function ShareWorkflowDialog({workflows,onClose,onPublished,initialId=""}:{workflows:{id:string;name:string}[];onClose:()=>void;onPublished:()=>void;initialId?:string}) {
 const [id,setId]=useState(initialId),[name,setName]=useState(workflows.find(w=>w.id===initialId)?.name || ""),[description,setDescription]=useState(""),[graph,setGraph]=useState<unknown>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" onKeyDown={e=>{if(e.key==="Escape"&&!busy)onClose();}}><form role="dialog" aria-modal="true" aria-label="上傳工作流至藍翼廣場" className="w-full max-w-lg space-y-4 rounded-2xl border border-neutral-700 bg-neutral-900 p-6" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/canvas/plaza",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,...(graph?{graph}:{workflowId:id})})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||"上傳失敗");onPublished();}catch(e){setError(e instanceof Error?e.message:"上傳失敗");}finally{setBusy(false);}}}>
 <h2 className="text-lg font-semibold">上傳／分享工作流</h2><p className="text-sm text-neutral-400">節點與提示詞將公開供其他使用者複製。私人素材及生成結果不會隨工作流分享，使用者可自行加入素材。</p>
 <label className="block text-sm">選擇我的畫布<select autoFocus className="mt-2 w-full rounded bg-neutral-800 p-2" value={id} onChange={e=>{setId(e.target.value);setGraph(null);setName(workflows.find(w=>w.id===e.target.value)?.name||"");}}><option value="">選擇畫布或上傳 JSON</option>{workflows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>
 <label className="block rounded-xl border border-dashed border-neutral-600 p-4 text-sm">上傳畫布 JSON（最多 3 MB）<input type="file" accept=".json,application/json" className="mt-2 block w-full" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError("");setGraph(null);try{if(f.size>3000000)throw new Error("檔案超過 3 MB");const j=JSON.parse(await f.text());const g=j.graph||j;if(!Array.isArray(g.nodes)||!Array.isArray(g.edges))throw new Error("請上傳畫布匯出的 JSON 檔案");setGraph(g);setId("");setName(j.name||f.name.replace(/\.json$/i,""));}catch(e){setError(e instanceof Error?e.message:"無法讀取檔案");}}}/>{graph!=null&&<span className="mt-2 block text-emerald-300">工作流已讀取，確認名稱後即可上傳。</span>}</label>
 <label className="block text-sm">分享名稱<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded bg-neutral-800 p-2"/></label><label className="block text-sm">說明<textarea maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 w-full rounded bg-neutral-800 p-2"/></label>
 {error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<div className="flex justify-end gap-3"><button type="button" disabled={busy} onClick={onClose}>取消</button><button disabled={busy||(!id&&!graph)||!name.trim()} className="rounded-full bg-emerald-300 px-4 py-2 text-black disabled:opacity-40">{busy?"上傳中…":"公開分享到藍翼廣場"}</button></div></form></div>;
}
