import Link from "next/link";
import { PLANS } from "@/lib/plans";
import { CREDIT_PACKS } from "@/lib/creditPacks";
const COPY: Record<string,{eyebrow:string;description:string;features:string[]}>={
 free:{eyebrow:"從靈感開始",description:"輕鬆探索你的第一個作品。",features:["每天領取 10 點","依點數體驗生成","建立你的智慧畫布"]},
 basic:{eyebrow:"日常創作",description:"為偶爾湧現的靈感，留一點空間。",features:["每期 900 點","圖片、影片與文字創作","智慧畫布工作流程"]},
 standard:{eyebrow:"穩定產出",description:"讓系列作品，成為你的日常。",features:["每期 3,200 點","圖片、影片與文字創作","智慧畫布工作流程"]},
 premium:{eyebrow:"完整創作體驗",description:"為更大的故事，準備更多可能。",features:["每期 11,000 點","圖片、影片與文字創作","智慧畫布工作流程","解鎖陪聊角色專屬場景生成"]}
};
export default function PricingPage(){return <div className="h-full overflow-y-auto bg-[#080909] text-white"><div className="mx-auto max-w-[1560px] px-4 py-12 sm:px-8 lg:py-16">
<header className="mx-auto mb-10 max-w-2xl text-center"><p className="text-xs font-medium tracking-[.3em] text-[#7ff0cd]">BLUE WING · MEMBERSHIP</p><h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl"><span className="block">為你的下一個作品，</span><span className="mt-2 block">選擇更多可能。</span></h1><p className="mt-5 text-sm leading-7 text-neutral-400">從第一個靈感，到完整的創作計畫。<br/>選擇適合自己的點數額度，自由安排每一次生成。</p><span className="mt-6 inline-block rounded-full border border-neutral-700 bg-neutral-900 px-5 py-2 text-xs text-neutral-300">月方案 · 美元 USD</span></header>
<div className="grid items-stretch gap-4 sm:grid-cols-2 xl:grid-cols-4">{PLANS.map(p=>{const special=p.code==="standard",gold=p.code==="premium",c=COPY[p.code];return <section key={p.code} className={`flex flex-col rounded-[24px] border p-[1px] ${gold?"border-[#dfbf72] bg-gradient-to-br from-[#ffedb2] to-[#e2b854]":special?"border-[#b3c8dc] bg-gradient-to-br from-[#eff6ff] to-[#aabfd5]":"border-[#303333] bg-[#222525]"}`}>
<div className={`flex h-9 items-center justify-center text-xs font-semibold ${special||gold?"text-[#182029]":"text-neutral-400"}`}>{special?"✦ 推薦創作方案":gold?"✦ 更多點數・完整體驗":c.eyebrow}</div>
<div className={`flex flex-1 flex-col rounded-[21px] p-5 lg:p-6 ${gold?"bg-gradient-to-b from-[#292115] to-[#111313]":"bg-[#111313]"}`}>
<h2 className="text-xl font-semibold">{p.name}</h2><p className="mt-2 min-h-10 text-xs leading-5 text-neutral-400">{c.description}</p><div className="mt-5 flex items-baseline gap-2"><span className="text-5xl font-semibold tracking-tight">${p.priceUSD}</span><span className="text-xs text-neutral-400">{p.priceUSD?"/ 月":"免費"}</span></div><p className="mt-3 text-xs text-neutral-500">{p.priceUSD?"由管理員協助開通本期方案":"每日點數，不累積至隔日"}</p>
<Link href={p.code==="free"?"/register":"/account"} className={`mt-6 rounded-full px-4 py-3 text-center text-sm font-semibold text-black transition hover:brightness-110 ${gold?"bg-gradient-to-r from-[#fff0c0] to-[#ffd665]":special?"bg-gradient-to-r from-white to-[#b4c8df]":"bg-[#e7e9e9]"}`}>{p.priceUSD?"查看開通方式":"開始免費創作"}</Link>
<div className="my-6 rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs text-neutral-400">{p.dailyCredits?"每日創作點數":"每期方案點數"}</p><p className="mt-2 text-3xl font-semibold">{(p.dailyCredits||p.monthlyCredits).toLocaleString()} <span className="text-xs font-normal text-neutral-400">點</span></p><div className="mt-4 flex justify-between border-t border-white/10 pt-3 text-xs"><span className="text-neutral-400">{p.priceUSD?"每點方案單價":"領取方式"}</span><span>{p.priceUSD?`US$ ${(p.priceUSD/p.monthlyCredits).toFixed(5)}`:"每日使用時領取"}</span></div></div>
<ul className="space-y-4 pb-4 text-sm text-neutral-300">{c.features.map(f=><li key={f} className="flex gap-3"><span className={gold?"text-[#eacb80]":"text-[#7ff0cd]"}>✓</span>{f}</li>)}</ul><p className="mt-auto pt-5 text-xs leading-5 text-neutral-500">{p.priceUSD?"依生成設定扣點；本期點數到期失效。":"生成前可查看所需點數。"}</p>
</div></section>})}</div>
<section className="mt-12 rounded-3xl border border-neutral-800 bg-[#101212] p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs tracking-widest text-[#7ff0cd]">EXTRA CREDITS</p><h2 className="mt-2 text-2xl font-semibold">靈感多一點，額度也多一點。</h2></div><p className="text-xs text-neutral-400">一次性增購 · 開通日起 730 天有效</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{CREDIT_PACKS.map(p=><Link href="/account" key={p.code} className="group rounded-2xl border border-neutral-700 bg-white/[.02] p-5 transition hover:border-[#7ff0cd]"><p className="text-xl font-semibold">{p.credits.toLocaleString()} <span className="text-xs text-neutral-400">點</span></p><div className="mt-4 flex items-center justify-between"><span className="text-[#7ff0cd]">US$ {p.priceUSD}</span><span className="text-neutral-500 group-hover:text-white">↗</span></div><p className="mt-2 text-xs text-neutral-500">每點 US$ {(p.priceUSD/p.credits).toFixed(4)}</p></Link>)}</div></section>
<div className="mx-auto mt-8 max-w-3xl text-center text-xs leading-6 text-neutral-500"><p>目前由管理員協助開通，尚未提供線上付款或自動扣款。請提供帳號 UID 與所選方案。</p><p>每日免費點數不累積；月方案點數依該期效期使用、不結轉。每次生成依模型、解析度與設定扣點，送出前可查看預估點數。</p></div>
</div></div>}
